inventario/urls.py
from django.urls import path

from . import views

app_name = 'inventario'

urlpatterns = [
  path('', views.IndexView, name='index'),
  path('login/', views.LoginView.as_view(), name='login'),
  path('logout/', views.LogoutView.as_view(), name='logout'),
  path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
  path('delete-product/<pk>', views.ProductDeleteView.as_view(), name='delete-product'),
  path('edit-product/<pk>', views.ProductUpdateView.as_view(), name='edit-product'),
  path('reportes/', views.ReportesView.as_view(), name='reportes'),
]

productos/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventario.urls')),
]

inventario/models.py
from django.db import models


class Category(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=500)
    description = models.CharField(max_length=500)
    status = models.SmallIntegerField(choices=[
        (1, 'Activo'),
        (2, 'Inactivo'),
    ], default=1)

    def __str__(self):
        return f'{self.code} - {self.name}'
    

class Product(models.Model):
    description = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.DecimalField(max_digits=10, decimal_places=2)

    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='category_products')

inventario/forms.py
from django.forms import ModelForm
from .models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

inventario/views.py
import json
from django.views.generic import TemplateView, UpdateView, CreateView, DeleteView
from inventario.models import Product, Category
from django.db.models import Sum, Count

from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

def IndexView(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy('inventario:dashboard'))
    else:
        return redirect(reverse_lazy('inventario:login'))


class LoginView(auth_views.LoginView):
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse_lazy('inventario:dashboard'))
        return super(LoginView, self).dispatch(request, *args, **kwargs)


class LogoutView(auth_views.LogoutView):
    pass


class DashboardView(LoginRequiredMixin, CreateView):
    template_name = 'dashboard.html'
    model = Product
    fields = "__all__"
    success_url = '/dashboard/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = '/dashboard/'
    template_name = 'delete.html'


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    fields = "__all__"
    template_name = "edit.html"
    success_url = "/dashboard/"

  
class ReportesView(LoginRequiredMixin, TemplateView):
    template_name = 'reportes.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = Category.objects.annotate(Count('category_products'))
        context['categories'] = json.dumps(
            [{"name": category.name, "products_count": category.category_products__count} for category in qs]
        )
        return context

inventario/templates/base.html
{% load static %}

<!doctype html>
<html>

<head>
	<!-- Latest compiled and minified JavaScript -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

	<title>ABC Productos</title>

	<style>
		.inline-80 {
			display: inline-block;
			width: 80px;
		}
	</style>
</head>

<body>

	{% block content %}
	{% endblock %}

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
		crossorigin="anonymous"></script>
</body>

</html>

inventario/templates/dashboard.html
{% extends 'base.html' %} {% load static %} {% block content %}

{% include 'parts/menu.html' %}
<div class="container mt-5" id="new-entry">
  <h3>Crear Producto</h3>
  <form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar" class="btn btn-success">
  </form>
</div>
<div class="container mt-5" id="listing">
  <h3>Lista de productos</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Codigo</th>
        <th>Descripcion</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Categoria</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
      <tr>
        <td>{{product.id}}</td>
        <td>{{product.description}}</td>
        <td>{{product.price}}</td>
        <td>{{product.stock}}</td>
        <td>{{product.category}}</td>
        <td>
          <a href="{% url 'inventario:edit-product' product.pk %}" class="btn btn-primary">Editar</a>
          <a href="{% url 'inventario:delete-product' product.pk %}" class="btn btn-danger">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

inventario/templates/delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <form method="post">{% csrf_token %}
    <h1>Seguro que quiere eliminar este producto "{{ object.id }} {{object.description}}"?</h1>
    <input class="btn btn-danger" type="submit" value="Confirmar">
  </form>
</div>
{% endblock %}

inventario/templates/edit.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar cambios" class="btn btn-danger">
  </form>
</div>
{% endblock %}

inventario/templates/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container" id="login-dialog">
  <form class="col-lg-4 col-lg-offset-4" style="border: 1px solid #aaa; text-align: center;" method="POST">
    {% csrf_token %}
    <div class="form-group">
      &nbsp;
    </div>
    <div class="form-group mb-2">
      <label>Username</label> &nbsp;
      <input type="text" name="username" />
    </div>
    <div class="form-group mb-2">
      <label>Password</label> &nbsp;
      <input type="password" name="password" />
    </div>
    <div class="form-group">
      <input type="submit" value="Login" class="btn btn-primary" />
    </div>
    {% if form.errors %}
    <div>Credenciales invalidas.</div>
    {% endif %}
  </form>
</div>
{% endblock %}

inventario/templates/parts/menu.html
<div class="container" id="menu">
  <a href="{% url 'inventario:dashboard' %}" class="btn btn-default">Productos</a> &nbsp; 
  <a href="{% url 'inventario:reportes' %}" class="btn btn-default">Reportes</a> &nbsp; 
  <a href="{% url 'inventario:logout' %}" class="btn btn-default">Cerrar sesión</a> &nbsp; 
</div>

inventario/templates/reportes.html
{% extends 'base.html' %} {% load static %} {% block content %}

{% include 'parts/menu.html' %}
<div>
  &nbsp;
</div>

<div class="container" id="listing">
  <h1>Productos por categoria</h1>
  <canvas id="grafica"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@latest/dist/Chart.min.js"></script>
<script>
  const $grafica = document.querySelector("#grafica");
  let categoriesData = "{{categories}}".replaceAll("&quot;", '"')
  categoriesData = JSON.parse(categoriesData)
  const etiquetas = categoriesData.map(c => c.name)
  new Chart($grafica, {
    type: 'bar',
    data: {
      labels: etiquetas,
      datasets: [
        {
          label: "Categorias",
          data: categoriesData.map(c => c.products_count),
          backgroundColor: 'rgba(54, 162, 235, 0.2)',
          borderColor: 'rgba(54, 162, 235, 1)',
          borderWidth: 1,
        }
      ]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }],
      },
    }
  });
</script>

{% endblock %}